<?php include('header.php') ?>
<div class="pbmit-title-bar-wrappereep">
			<div class="container">
				<div class="pbmit-title-bar-content">
					<div class="pbmit-title-bar-content-inner">
						<div class="pbmit-tbar">
							<div class="pbmit-tbar-inner container">
								<h1 class="pbmit-tbar-title">Product</h1>
							</div>
						</div>
						
					</div>
				  </div>
			    </div>
		 </div>
		 <section class="section-md">
				<div class="container "> 
					<div class="pbmit-heading-subheading text-center">
						<h4 class="pbmit-subtitle">Product</h4>
						<h2 class="pbmit-title">Produce Your Own Clean Save<br>our the Environment</h2>
					</div>
					<div class="row">
						<div class="col-md-4">
							<article class="pbmit-service-style-1">
								<div class="pbminfotech-post-item">
										<div class="pbmit-featured-wrapper">
										<img src="images/homepage-2/service/inv.jpg" class="img-fluid" alt="">
									</div>
									<div class="pbminfotech-box-content">
										<div class="pbmit-service-icon">
											<div class="pbmit-service-icon-wrapper">
												<i class="pbmit-greenly-icon pbmit-greenly-icon-sun"></i> 
											</div>
										</div>
										<div class="pbminfotech-box-content-inner">
											
											<h3 class="pbmit-service-title">
												<a href="javascript:void(0); ">Solar Inverter </a>
											</h3>
											<div class="pbmit-service-content">
												<p>A solar inverter, also known as a PV inverter or solar power inverter, is a device that converts direct current (DC) generated by solar panels.</p>
											</div>
											<div class="pbmit-service-btn">
												<div class="btn3-inline">
													<a href="javascript:void(0); " class="btn3-color-globalcolor">More</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</article>
						</div>
						<div class="col-md-4">
							<article class="pbmit-service-style-1">
								<div class="pbminfotech-post-item">
										<div class="pbmit-featured-wrapper">
										<img src="images/homepage-2/service/sba.jpg" class="img-fluid" alt="">
									</div>
									<div class="pbminfotech-box-content">
										<div class="pbmit-service-icon">
											<div class="pbmit-service-icon-wrapper">
												<i class="pbmit-greenly-icon pbmit-greenly-icon-solar-panel"></i>
											</div>
										</div>
										<div class="pbminfotech-box-content-inner">
											
											<h3 class="pbmit-service-title">
												<a href="javascript:void(0); ">Solar Batteries</a>
											</h3>
											<div class="pbmit-service-content">
												<p>Solar batteries, also known as solar energy storage systems or solar battery storage, are devices that store excess electricity.</p>
											</div>
											<div class="pbmit-service-btn">
												<div class="btn3-inline">
													<a href="javascript:void(0); " class="btn3-color-globalcolor">More</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</article>
						</div>
						<div class="col-md-4">
							<article class="pbmit-service-style-1">
								<div class="pbminfotech-post-item">
										<div class="pbmit-featured-wrapper">
										<img src="images/homepage-2/service/service-img-03.jpg" class="img-fluid" alt="">
									</div>
									<div class="pbminfotech-box-content">
										<div class="pbmit-service-icon">
											<div class="pbmit-service-icon-wrapper">
												<i class="pbmit-greenly-icon pbmit-greenly-icon-windmill"></i> 
											</div>
										</div>
										<div class="pbminfotech-box-content-inner">
											
											<h3 class="pbmit-service-title">
												<a href="javascript:void(0); ">Solar Panel</a>
											</h3>
											<div class="pbmit-service-content">
												<p>Solar panels, also known as photovoltaic (PV) panels, are devices that convert sunlight directly into electricity. </p>
											</div>
											<div class="pbmit-service-btn">
												<div class="btn3-inline">
													<a href="javascript:void(0); " class="btn3-color-globalcolor">More</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</article>
						</div>
					</div>
					
				</div>
			</section>



<?php include('footer.php') ?>